import random

cast_channels = [
    'https://warpcast.com/~/channel/music',
    'https://warpcast.com/~/channel/Memes',
    'https://warpcast.com/~/channel/dogs',
    'https://warpcast.com/~/channel/Food',
    'https://warpcast.com/~/channel/movie',
    'https://warpcast.com/~/channel/Nature',
    'https://warpcast.com/~/channel/Art',
    'https://warpcast.com/~/channel/Travel',
    'https://warpcast.com/~/channel/Photography',
    'https://warpcast.com/~/channel/Cats'
]

follow_channels = [
    'https://warpcast.com/~/channel/music',
    'https://warpcast.com/~/channel/Memes',
    'https://warpcast.com/~/channel/dogs',
    'https://warpcast.com/~/channel/Food',
    'https://warpcast.com/~/channel/movie',
    'https://warpcast.com/~/channel/Nature',
    'https://warpcast.com/~/channel/Art',
    'https://warpcast.com/~/channel/Travel',
    'https://warpcast.com/~/channel/Photography',
    'https://warpcast.com/~/channel/Cats',
    'https://warpcast.com/~/channel/Degen',
    'https://warpcast.com/~/channel/Farcaster',
    'https://warpcast.com/~/channel/itookaphoto',
    'https://warpcast.com/~/channel/replyguys',
    'https://warpcast.com/~/channel/rodeo-club',
    'https://warpcast.com/~/channel/yoink',
    'https://warpcast.com/~/channel/Warpcast',
    'https://warpcast.com/~/channel/nuts',
    'https://warpcast.com/~/channel/degenfans',
    'https://warpcast.com/~/channel/sense',
    'https://warpcast.com/~/channel/to-me',
    'https://warpcast.com/~/channel/SuperRare',
    'https://warpcast.com/~/channel/pkok',
    'https://warpcast.com/~/channel/airstack',
    'https://warpcast.com/~/channel/hype-up',
    'https://warpcast.com/~/channel/Art',
    'https://warpcast.com/~/channel/Jobs',
    'https://warpcast.com/~/channel/layer3',
    'https://warpcast.com/~/channel/farville',
    'https://warpcast.com/~/channel/moxie-korea',
    'https://warpcast.com/~/channel/farcade',
    'https://warpcast.com/~/channel/GM',
    'https://warpcast.com/~/channel/diet',
    'https://warpcast.com/~/channel/kimchi',
    'https://warpcast.com/~/channel/ai-art',
    'https://warpcast.com/~/channel/Founders',
    'https://warpcast.com/~/channel/mass-effect',
    'https://warpcast.com/~/channel/lifeisgood',
    'https://warpcast.com/~/channel/cryptoart',
    'https://warpcast.com/~/channel/hoiaefarcastervn',
    'https://warpcast.com/~/channel/lp',
    'https://warpcast.com/~/channel/innerview',
    'https://warpcast.com/~/channel/replyors',
    'https://warpcast.com/~/channel/Base',
    'https://warpcast.com/~/channel/lifechanger',
    'https://warpcast.com/~/channel/anime-manga',
    'https://warpcast.com/~/channel/politics',
    'https://warpcast.com/~/channel/banmal-mode',
    'https://warpcast.com/~/channel/degen-art',
    'https://warpcast.com/~/channel/dev',
    'https://warpcast.com/~/channel/Travel',
    'https://warpcast.com/~/channel/whysoserious',
    'https://warpcast.com/~/channel/whoami',
    'https://warpcast.com/~/channel/bart',
    'https://warpcast.com/~/channel/veg'
]

power_users = [
    'https://warpcast.com/amaliee.eth',
    'https://warpcast.com/dwr.eth',
    'https://warpcast.com/superanon',
    'https://warpcast.com/jacek',
    'https://warpcast.com/jessepollak',
    'https://warpcast.com/ted',
    'https://warpcast.com/thienthanh064',
    'https://warpcast.com/thaonguyen754',
    'https://warpcast.com/boyhx',
    'https://warpcast.com/mayhuttinh',
    'https://warpcast.com/thaovy385',
    'https://warpcast.com/tbddegen',
    'https://warpcast.com/hoangthuy',
    'https://warpcast.com/woj.eth',
    'https://warpcast.com/pickdegen',
    'https://warpcast.com/tibi12',
    'https://warpcast.com/mybinh',
    'https://warpcast.com/duongdungg',
    'https://warpcast.com/thuthao768',
    'https://warpcast.com/hieukhanh',
    'https://warpcast.com/artbysalman',
    'https://warpcast.com/betashop.eth',
    'https://warpcast.com/frvnk',
    'https://warpcast.com/trillobyte',
    'https://warpcast.com/kaie',
    'https://warpcast.com/v',
    'https://warpcast.com/lct',
    'https://warpcast.com/nimaleophotos.eth',
    'https://warpcast.com/alvi-ayaan',
    'https://warpcast.com/eriks',
    'https://warpcast.com/gulyildiz',
    'https://warpcast.com/cubjs',
    'https://warpcast.com/nothing11',
    'https://warpcast.com/thedude',
    'https://warpcast.com/macster',
    'https://warpcast.com/carla5562',
    'https://warpcast.com/bay-photography',
    'https://warpcast.com/ihawaii.eth',
    'https://warpcast.com/pichi',
    'https://warpcast.com/inceptionally',
    'https://warpcast.com/proxystudio.eth',
    'https://warpcast.com/kylepatrick.eth',
    'https://warpcast.com/sohan0323',
    'https://warpcast.com/avaaaaart',
    'https://warpcast.com/trebor69',
    'https://warpcast.com/keccers.eth',
    'https://warpcast.com/july',
    'https://warpcast.com/zthaiha785',
    'https://warpcast.com/degentoken',
    'https://warpcast.com/lunamarsh',
    'https://warpcast.com/mehrad',
    'https://warpcast.com/horsefacts.eth',
    'https://warpcast.com/cassie',
    'https://warpcast.com/kenjiquest',
    'https://warpcast.com/hellena',
    'https://warpcast.com/basecrypto66',
    'https://warpcast.com/six',
    'https://warpcast.com/cuuxjnhdep',
    'https://warpcast.com/icetoad.eth',
    'https://warpcast.com/maryamm13',
    'https://warpcast.com/honghoa98',
    'https://warpcast.com/yenthi',
    'https://warpcast.com/kimhoang',
    'https://warpcast.com/tuminh',
    'https://warpcast.com/hanayon',
    'https://warpcast.com/thanhga',
    'https://warpcast.com/tranha',
    'https://warpcast.com/juliaphm',
    'https://warpcast.com/ronata',
    'https://warpcast.com/mib9',
    'https://warpcast.com/seutabbi',
    'https://warpcast.com/jangs',
    'https://warpcast.com/thanhga439',
    'https://warpcast.com/georgesoky',
    'https://warpcast.com/nftsariyildiz',
    'https://warpcast.com/postingls',
    'https://warpcast.com/rinanatelee',
    'https://warpcast.com/mainhi66',
    'https://warpcast.com/phamphuqui',
    'https://warpcast.com/bichlien6',
    'https://warpcast.com/alaine',
    'https://warpcast.com/hungxedap',
    'https://warpcast.com/mylan',
    'https://warpcast.com/luuthuy77',
    'https://warpcast.com/halinh999',
    'https://warpcast.com/hangpham',
    'https://warpcast.com/yurilee',
    'https://warpcast.com/thuantienty',
    'https://warpcast.com/keoasia',
    'https://warpcast.com/adriannae',
    'https://warpcast.com/phamvanminh',
    'https://warpcast.com/nickdang',
    'https://warpcast.com/quangem',
    'https://warpcast.com/vyytay',
    'https://warpcast.com/yonfrula',
    'https://warpcast.com/bichngoc87',
    'https://warpcast.com/dragonbaby',
    'https://warpcast.com/sanadia',
    'https://warpcast.com/lequyen',
    'https://warpcast.com/quanghai',
]
def get_cast_channel(key: str):

    for cast_channel in cast_channels:
        if key in cast_channel:
            return cast_channel
    return None


x_map = {
    'cast_channel_select': '//div[@id="modal-root"]/div/div/div/div/div[2]/span[1]/div/div[2]/div/div[1]/span/div',
    'first_search_channel': '//div[@data-side="bottom"]/div/div[3]/div[1]',
    # //*[@id="root"]/div/div/div/main/div/div/div[2]/div[2]/div/div/div[3]/div/div/div[3]/div[1]/button/div
    'recast': '//div[3]/div[1]/button/div',
    'like': '//div[3]/div[1]/div[2]',
    'recast_single': '//div[1]/div/div[2]/div/div[2]/div',
    'like_single': '//div[1]/div/div[2]/div/div[2]/div[2]',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9'
}

tw_follow_list = [
]
